"""empty message

Revision ID: 19b8cacf4d34
Revises: fcba8824bf8d
Create Date: 2021-02-02 13:25:40.539629

"""

# revision identifiers, used by Alembic.
revision = '19b8cacf4d34'
down_revision = 'fcba8824bf8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('handler', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'handler')
    # ### end Alembic commands ###
