"""Add User model

Revision ID: 2acc88805404
Revises: d6de0409fc74
Create Date: 2017-10-16 12:01:26.692076

"""

# revision identifiers, used by Alembic.
revision = '2acc88805404'
down_revision = 'd6de0409fc74'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
