"""Add manual_triggered to Event model

Revision ID: 2f5a2f4385a0
Revises: 2acc88805404
Create Date: 2017-11-01 14:03:02.555397

"""

# revision identifiers, used by Alembic.
revision = '2f5a2f4385a0'
down_revision = '2acc88805404'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('manual_triggered', sa.Boolean()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'manual_triggered')
    ### end Alembic commands ###
