"""empty message

Revision ID: 300b86758bb1
Revises: bfc0e0d2eea6
Create Date: 2017-09-14 07:41:45.501531

"""

# revision identifiers, used by Alembic.
revision = '300b86758bb1'
down_revision = 'bfc0e0d2eea6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_dependency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_dependency_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_dependencies')
    # ### end Alembic commands ###
