"""Add search_key and event_type_id to events

Revision ID: 85906960545
Revises: 1529069af28e
Create Date: 2017-06-01 08:09:30.207251

"""

# revision identifiers, used by Alembic.
revision = '85906960545'
down_revision = '1529069af28e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_type_id', sa.Integer(), nullable=False))
    op.add_column('events', sa.Column('search_key', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'search_key')
    op.drop_column('events', 'event_type_id')
    ### end Alembic commands ###
