"""Add compose_id to Event

Revision ID: bfc0e0d2eea6
Revises: 43b3c6580af7
Create Date: 2017-09-08 16:47:14.882980

"""

# revision identifiers, used by Alembic.
revision = 'bfc0e0d2eea6'
down_revision = '43b3c6580af7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('compose_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'compose_id')
    ### end Alembic commands ###
