"""Add unique constraint to Compose.odcs_compose_id

Revision ID: e06434b3ef5e
Revises: b17231ee8220
Create Date: 2017-12-27 14:53:42.321947

"""

# revision identifiers, used by Alembic.
revision = 'e06434b3ef5e'
down_revision = 'b17231ee8220'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_odcs_compose_id', 'composes', ['odcs_compose_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_odcs_compose_id', table_name='composes')
    # ### end Alembic commands ###
