"""Add unique index to EventDependency

Revision ID: f3223db11e48
Revises: e06434b3ef5e
Create Date: 2018-01-04 09:45:25.153391

"""

# revision identifiers, used by Alembic.
revision = 'f3223db11e48'
down_revision = 'e06434b3ef5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_event_dependency_rel', 'event_dependencies', ['event_id', 'event_dependency_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_event_dependency_rel', table_name='event_dependencies')
    # ### end Alembic commands ###
