name: Docs

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-22.04
    env:
      RPM_PY_SYS: true
    steps:
      - uses: actions/checkout@v4

      - name: Disable Jekyll
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: mkdir -p docs/_build/html/ && touch docs/_build/html/.nojekyll

      - name: Get package list
        id: packages
        shell: bash
        run: |
          echo ::set-output name=packages::$(sed 's/#.*//' yum-packages-devel.txt)

      - name: Build docs
        uses: fedora-python/tox-github-action@v38.0
        with:
          dnf_install: ${{ steps.packages.outputs.packages }}
          tox_env: docs

      - name: Deploy docs
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          branch: gh-pages
          folder: docs/_build/html
