name: Docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-18.04
    env:
      RPM_PY_SYS: true
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get -y install koji-client libkrb5-dev libldap2-dev libsasl2-dev librpm-dev rpm 
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install Tox
        run: pip install tox
      - name: Build docs
        run: tox -e docs
      - name: Disable Jekyll
        run: touch docs/_build/html/.nojekyll
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: docs/_build/html
